version: '3'                                         # Specify the version of the Docker Compose file format

services:                                            # Define the services (containers) to be run
  jaffnakid:
    build: ./jaffnakid
    #image: thanushan:latest                          # Use the latest image of thanushan
    container_name: jaffnakid                        # Name the container 'jaffnakid'
    # ports:
    #   - "5001:5000"                                ### Uncomment to map port 5001 on the host to port 5000 in the container
    networks:
      - app-router                                   # Connect this service to the 'app-router' network

  wellawattakid:
    build: ./wellawattakid
    #image: thanushan:v1.0                            # Use version 1.0 of the thanushan image
    container_name: wellawattakid                    # Name the container 'wellawattakid'
    # ports:
    #   - "5002:5000"                                ### Uncomment to map port 5002 on the host to port 5000 in the container
    networks:
      - app-router                                   # Connect this service to the 'app-router' network

  nginx:
    image: nginx:latest                              # Use the latest nginx image
    container_name: nginx-lb                         # Name the container 'nginx-lb'
    ports:
      - "8088:80"                                    # Map port 8088 on the host to port 80 in the container
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf           # Mount the local nginx.conf file to the container
    networks:
      - app-router                                   # Connect this service to the 'app-router' network

networks:                                            # Define custom networks
  app-router:                                        # Name of the custom network
    driver: bridge                                   # Use the bridge driver for this network
